import Head from "next/head";
import Image from "next/image";
import Avatar from "../components/Avatar";
import { MicrophoneIcon, ViewGridIcon } from "@heroicons/react/solid";
import { SearchIcon, XIcon } from "@heroicons/react/outline";
import Footer from "../components/Footer";
import { useRef, useState } from "react";
import { useRouter } from "next/router";

export default function Home() {
  const router = useRouter();

  const searchInputRef = useRef();

  const search = (e) => {
    e.preventDefault();
    const terms = searchInputRef.current.value;
    // console.log(terms);
    if (!terms) {
      return;
    } else {
      router.push(`/search?term=${terms}`);
    }
  };

  return (
    <div className="flex flex-col justify-center h-screen">
      <Head>
        <title>google</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      {/* header */}

      <header className="flex w-full p-5 justify-between text-sm text-gray-500">
        {/* left */}
        <div className="flex space-x-4 items-center">
          <p className="link">About</p>
          <p className="link">Store</p>
        </div>
        {/* right */}
        <div className="flex space-x-4 items-center">
          <p className="link">Gmail</p>
          <p className="link">Images</p>
          {/* Icon */}
          <ViewGridIcon className="h-10 w-10 p-2 rounded-full hover:bg-gray-200 cursor-pointer" />
          {/* Avatar */}
          <Avatar url="https://sirilmp.online/img/profile.png" />
        </div>
      </header>

      {/* body */}
      <form className="flex flex-col items-center mt-44 flex-grow">
        <Image
          src="https://www.google.com/images/branding/googlelogo/1x/googlelogo_color_272x92dp.png"
          height={100}
          width={300}
        />
        <div className="flex w-full mt-5 hover:shadow-lg focus-within:shadow-lg max-w-md rounded-full border border-gray-200 px-5 py-3 items-center sm:max-w-xl lg:max-w-2xl">
          <SearchIcon className="h-5 mr-3 text-gray-500" />
          <input
            ref={searchInputRef}
            type="text"
            className="flex-grow focus:outline-none "
          />
      <XIcon
            onClick={() => (searchInputRef.current.value = "")}
            className="h-6 cursor-pointer text-gray-500 transition duration-100 transform hover:scale-125 sm:mr-3"
          />
          <MicrophoneIcon className="h-6 mr-3  text-blue-500" />
        </div>
        <div className="mt-3 flex flex-col space-y-1 justify-center sm:space-y-0 sm:flex-row">
          <button onClick={search} className="btn">
            Google Search
          </button>
          <button onClick={search} className="btn">
            I'm Feeling Lucky
          </button>
        </div>
      </form>
      {/* footer */}
      <Footer />
    </div>
  );
}
